app/assets/javascripts/cable.js

demo.kazuya

---

Gemfile

##What
practice
##Why
practice

demo.hirabayashi

---

Gemfile
Gemfile.lock
config/unicorn.rb

deploy-first

---

app/assets/javascripts/items.coffee
app/assets/stylesheets/items.scss
app/controllers/items_controller.rb
app/helpers/items_helper.rb
app/models/item.rb
app/models/user.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb
db/migrate/20191120051248_create_items.rb
db/migrate/20191120051408_devise_create_users.rb
test/controllers/items_controller_test.rb
test/fixtures/items.yml
test/fixtures/users.yml
test/models/item_test.rb
test/models/user_test.rb

##What
create items controller
create item model
install devise
create user model
##Why
フロント実装の準備

コントローラ、モデル作成

---

Gemfile
config/unicorn.rb

unicorn setup

---

config/initializers/devise.rb

##What
db migrateがうまく行かないエラーを修正
##Why
エラー解消

db migrateとエラー修正

---

Gemfile

##What
gemファイル内
gem 'sqlite3'の末尾にあるコンマを削除
##Why
Syntax error解消

revise error

---

config/database.yml

database.ymlの本番環境の設定
本番環境でアプリを起動させるため

unicorn-setup

---

app/views/users/confirmations/new.html.erb
app/views/users/mailer/confirmation_instructions.html.erb
app/views/users/mailer/email_changed.html.erb
app/views/users/mailer/password_change.html.erb
app/views/users/mailer/reset_password_instructions.html.erb
app/views/users/mailer/unlock_instructions.html.erb
app/views/users/passwords/edit.html.erb
app/views/users/passwords/new.html.erb
app/views/users/registrations/edit.html.erb
app/views/users/registrations/new.html.erb
app/views/users/sessions/new.html.erb
app/views/users/shared/_error_messages.html.erb
app/views/users/shared/_links.html.erb
app/views/users/unlocks/new.html.erb

add devise view

---

app/assets/stylesheets/users.scss
app/views/users/edit-profile.html.haml

#what
ユーザー返信ページの実装（ヘッダー、サイドリストは後にrenderにより付け加えます）
#why
実装確認のため

edit-profilepage

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/logout.scss
app/views/items/index.html.haml

logout-page

---

app/assets/stylesheets/new-myprofile-akkunn.scss
app/views/users/new-myprofile-akkunn.html.haml

##what
本人登録画面の実装のため
##why
実装のため

add-new-myprofile

---

config/deploy.rb

s3設定　
本番環境のshared/configにmaster.keyを作成するため

s3-setting3

---

README.md

##What
readmeにDB設計を記載
以前masterにmerge済みのためreadmeのbranchを参照してください
##Why
DB設計のコードレビュー

readmeにDB設計を記載

---

app/assets/stylesheets/items_show-bayashi.scss
app/views/items/show.html.haml

items-show-page

---

app/assets/stylesheets/product-buy-page-akkunn.scss
app/views/users/product-buy-page-akkunn.html.haml

what
商品購入ページの実装
why
実装画面の確認してもらうため
[![Screenshot from Gyazo](https://gyazo.com/b1fbefa687f4d74be5600febff5021ad/raw)](https://gyazo.com/b1fbefa687f4d74be5600febff5021ad)

product-buy-page

---

db/migrate/20191120051248_create_items.rb

Item.migrate

---

app/assets/stylesheets/_reset.scss
app/assets/stylesheets/items.scss
app/assets/stylesheets/show.scss
app/controllers/items_controller.rb
app/views/items/index.html.haml
app/views/items/show.html.haml

items-show-action

---

app/controllers/cards_controller.rb

cards_controller.rbの変更
本番環境にてクレジットカード情報登録のため

payjp fix2

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/item.scss
app/views/items/new.html.haml

items.view

---

app/controllers/items_controller.rb
app/views/items/show.html.haml
config/routes.rb

ルート微修正、showpage微調整
ルート微修正、showpage微調整

routes-fix

---

app/uploaders/images_uploader.rb

images_upoloaderの修正
画像をS3に保存するため

s3-resetting

---

config/initializers/carrierwabe.rb

carrierwave.rb の記述を微調整
本番環境でS3に保存した画像を表示させるため

s3-resseting2

---

app/assets/stylesheets/items.scss
app/views/items/_item.html.haml
app/views/items/index.html.haml

index.view

---

app/controllers/items_controller.rb

prefecture.edit

---

config/environments/production.rb

production.rbの変更
本番環境にて購入後のsold状態を表示させるため

asset-pipeline

---

app/controllers/application_controller.rb
config/deploy/production.rb

basic-admin

---

app/assets/stylesheets/item.scss
app/assets/stylesheets/show.scss
app/controllers/items_controller.rb
app/controllers/users_controller.rb
app/views/items/edit.heml.haml
app/views/items/edit.html.haml
app/views/users/mypage.html.haml
app/views/users/mypage_items.html.haml
app/views/users/shared/_side-bar.html.haml
config/routes.rb

items-edit-destroy

---

app/assets/stylesheets/items.scss
app/views/items/index.html.haml
app/views/users/shared/_header.html.haml

headerにアイコン付与

---

app/views/users/index.html.haml
app/views/users/mypage.html.haml
app/views/users/shared/_header.html.haml

mypage微調整
headerのpath変更
mypage微調整
headerのpath変更

view-fix-2

---

app/models/item.rb

destroy-action-fix

---

app/assets/stylesheets/_mypage.scss

backgroud-image-fix
